apiVersion: v1
kind: Pod
metadata:
  name: guestbook-pod
  labels:
    app: guestbook-app
spec:
  containers:
  - name: guestbook-python
    image: guestbook-python:v1
    ports:
    - containerPort: 80
  - name: guestbook-redis
    image: redis:alpine
    volumeMounts:
    - mountPath: /data
      name: redis-data
  volumes:
  - name: redis-data
    persistentVolumeClaim:
      claimName: guestbook-pvc

---

apiVersion: v1
kind: Service
metadata:
  name: guestbook-svc
  labels:
    app: guestbook-app
spec:
  type: NodePort
  selector:
    app: guestbook-app
  ports:
  - port: 8080
    targetPort: 80

