apiVersion: v1
kind: Service
metadata:
  name: hello-app-svc-nodeport
  labels:
    app: hello-app
spec:
  type: NodePort
  selector:
    app: hello-app
    tier: frontend
  ports:
  - port: 80
    targetPort: 8080
